version: '3'
services:
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: survey-api
    build: .
    image: survey-api
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/survey-api/dist
    ports:
      - '5051:5051'
    links:
      - mongo